packages:
  - "packages/*"
allowBuilds:
  esbuild: false
  sharp: true
  spawn-sync: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - "@my-react/react-dom@0.3.30"
  - "@my-react/react-jsx@0.3.30"
  - "@my-react/react-refresh@0.3.30"
  - "@my-react/react-terminal@0.0.30"
  - "@my-react/react-vite@0.0.36"
  - "@my-react/react@0.3.30"
  - ink-stream-markdown@0.0.8
  - "@git-diff-view/core@0.1.7"
  - "@git-diff-view/file@0.1.7"
  - "@git-diff-view/lowlight@0.1.7"
  - "@git-diff-view/cli@0.1.10"
  - "@tanstack/ai-client@0.26.0"
  - "@tanstack/ai-openai@0.21.1"
  - "@tanstack/ai@0.48.0"
  - "@tanstack/openai-base@0.10.3"
  - "@tanstack/ai-mcp@0.3.4"
  - "@tanstack/ai-anthropic@0.17.1"

publicHoistPattern:
  - "*eslint-*"
  - "*@heroui/*"
  - "*@my-react/*"
  - "*@my-agent/*"
