packages:
  - "packages/*"
allowBuilds:
  "@heroui/shared-utils": true
  "@mongodb-js/zstd": true
  esbuild: false
  node-liblzma: false
  sharp: true
  spawn-sync: false
  unrs-resolver: false

publicHoistPattern:
  - "*eslint-*"
  - "*@heroui/*"
  - "*@my-react/*"
  - "*@my-agent/*"
