import type { ModelId, ModelInfo } from "../types.js";

export const anthropicModels: Record<ModelId, ModelInfo> = {
  "claude-opus-4.8": {
    id: "claude-opus-4.8",
    name: "Claude Opus 4.8",
    provider: "anthropic",
    apiModel: "claude-opus-4-8",
    contextWindow: 1_000_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 5.0,
      outputPerM: 25.0,
      cacheWritePerM: 6.25,
      cacheReadPerM: 0.5,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output", "computer_use"],
    reasoningConfig: { defaultEffort: "high" },
    isDefault: false,
  },
  "claude-opus-4.7": {
    id: "claude-opus-4.7",
    name: "Claude Opus 4.7",
    provider: "anthropic",
    apiModel: "claude-opus-4-7",
    contextWindow: 1_000_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 5.0,
      outputPerM: 25.0,
      cacheWritePerM: 6.25,
      cacheReadPerM: 0.5,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output", "computer_use"],
    reasoningConfig: { defaultEffort: "high" },
    isDefault: false,
  },
  "claude-sonnet-4.6": {
    id: "claude-sonnet-4.6",
    name: "Claude Sonnet 4.6",
    provider: "anthropic",
    apiModel: "claude-sonnet-4-6",
    contextWindow: 1_000_000,
    defaultMaxTokens: 64_000,
    pricing: {
      inputPerM: 3.0,
      outputPerM: 15.0,
      cacheWritePerM: 3.75,
      cacheReadPerM: 0.3,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output", "computer_use"],
    reasoningConfig: { defaultEffort: "medium" },
    isDefault: true,
  },
  "claude-sonnet-4.5": {
    id: "claude-sonnet-4.5",
    name: "Claude Sonnet 4.5",
    provider: "anthropic",
    apiModel: "claude-sonnet-4-5-20250929",
    contextWindow: 200_000,
    defaultMaxTokens: 64_000,
    pricing: {
      inputPerM: 3.0,
      outputPerM: 15.0,
      cacheWritePerM: 3.75,
      cacheReadPerM: 0.3,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output", "computer_use"],
    reasoningConfig: { defaultEffort: "medium" },
    isDefault: false,
  },
  "claude-haiku-4.5": {
    id: "claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    apiModel: "claude-haiku-4-5-20251001",
    contextWindow: 200_000,
    defaultMaxTokens: 64_000,
    pricing: {
      inputPerM: 1.0,
      outputPerM: 5.0,
      cacheWritePerM: 1.25,
      cacheReadPerM: 0.1,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output", "computer_use"],
    reasoningConfig: { defaultEffort: "low" },
    isDefault: false,
  },
};
