import type { ModelId, ModelInfo } from "../types.js";

export const deepseekModels: Record<ModelId, ModelInfo> = {
  "deepseek-v4-flash": {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "deepseek",
    apiModel: "deepseek-v4-flash",
    contextWindow: 1_048_576,
    defaultMaxTokens: 393_216,
    pricing: {
      inputPerM: 0.14,
      outputPerM: 0.28,
      cacheReadPerM: 0.0028,
    },
    capabilities: ["reasoning", "tool_calling", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "medium" },
    isDefault: true,
  },
  "deepseek-v4-pro": {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "deepseek",
    apiModel: "deepseek-v4-pro",
    contextWindow: 1_048_576,
    defaultMaxTokens: 393_216,
    pricing: {
      inputPerM: 0.435,
      outputPerM: 0.87,
      cacheReadPerM: 0.003625,
    },
    capabilities: ["reasoning", "tool_calling", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "high" },
    isDefault: false,
  },
  "deepseek-chat": {
    id: "deepseek-chat",
    name: "DeepSeek Chat (V4 Flash alias)",
    provider: "deepseek",
    apiModel: "deepseek-chat",
    contextWindow: 1_048_576,
    defaultMaxTokens: 393_216,
    pricing: {
      inputPerM: 0.14,
      outputPerM: 0.28,
      cacheReadPerM: 0.0028,
    },
    capabilities: ["tool_calling", "streaming", "json_output"],
    isDefault: false,
  },
  "deepseek-reasoner": {
    id: "deepseek-reasoner",
    name: "DeepSeek Reasoner (V4 Flash alias)",
    provider: "deepseek",
    apiModel: "deepseek-reasoner",
    contextWindow: 1_048_576,
    defaultMaxTokens: 393_216,
    pricing: {
      inputPerM: 0.14,
      outputPerM: 0.28,
      cacheReadPerM: 0.0028,
    },
    capabilities: ["reasoning", "tool_calling", "streaming", "json_output"],
    reasoningConfig: { tagName: "think" },
    isDefault: false,
  },
};
