import type { ModelId, ModelInfo } from "../types.js";

export const openaiModels: Record<ModelId, ModelInfo> = {
  // ── GPT-5.5 family ──────────────────────────────────────────────────────────
  "gpt-5.5": {
    id: "gpt-5.5",
    name: "GPT-5.5",
    provider: "openai",
    apiModel: "gpt-5.5",
    contextWindow: 1_050_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 5.0,
      outputPerM: 30.0,
      cacheReadPerM: 0.5,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "medium" },
    isDefault: true,
  },

  // ── GPT-5.4 family ──────────────────────────────────────────────────────────
  "gpt-5.4": {
    id: "gpt-5.4",
    name: "GPT-5.4",
    provider: "openai",
    apiModel: "gpt-5.4",
    contextWindow: 1_050_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 2.5,
      outputPerM: 15.0,
      cacheReadPerM: 0.25,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "low" },
    isDefault: false,
  },
  "gpt-5.4-mini": {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    provider: "openai",
    apiModel: "gpt-5.4-mini",
    contextWindow: 400_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 0.75,
      outputPerM: 4.5,
      cacheReadPerM: 0.075,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "low" },
    isDefault: false,
  },
  "gpt-5.4-nano": {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    provider: "openai",
    apiModel: "gpt-5.4-nano",
    contextWindow: 400_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 0.2,
      outputPerM: 1.25,
      cacheReadPerM: 0.02,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "low" },
    isDefault: false,
  },

  // ── GPT-4.1 family ──────────────────────────────────────────────────────────
  "gpt-4.1": {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    apiModel: "gpt-4.1",
    contextWindow: 1_047_576,
    defaultMaxTokens: 32_768,
    pricing: {
      inputPerM: 2.0,
      outputPerM: 8.0,
      cacheReadPerM: 0.5,
    },
    capabilities: ["vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    isDefault: false,
  },
  "gpt-4.1-mini": {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    provider: "openai",
    apiModel: "gpt-4.1-mini",
    contextWindow: 1_047_576,
    defaultMaxTokens: 32_768,
    pricing: {
      inputPerM: 0.4,
      outputPerM: 1.6,
      cacheReadPerM: 0.1,
    },
    capabilities: ["vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    isDefault: false,
  },
  "gpt-4.1-nano": {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    provider: "openai",
    apiModel: "gpt-4.1-nano",
    contextWindow: 1_047_576,
    defaultMaxTokens: 32_768,
    pricing: {
      inputPerM: 0.1,
      outputPerM: 0.4,
      cacheReadPerM: 0.025,
    },
    capabilities: ["vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    isDefault: false,
  },

  // ── o-series reasoning models ───────────────────────────────────────────────
  o3: {
    id: "o3",
    name: "o3",
    provider: "openai",
    apiModel: "o3",
    contextWindow: 200_000,
    defaultMaxTokens: 100_000,
    pricing: {
      inputPerM: 2.0,
      outputPerM: 8.0,
      cacheReadPerM: 0.5,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "medium" },
    isDefault: false,
  },
  "o4-mini": {
    id: "o4-mini",
    name: "o4 Mini",
    provider: "openai",
    apiModel: "o4-mini",
    contextWindow: 200_000,
    defaultMaxTokens: 100_000,
    pricing: {
      inputPerM: 1.1,
      outputPerM: 4.4,
      cacheReadPerM: 0.275,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "medium" },
    isDefault: false,
  },

  // ── GPT-4o family (legacy) ──────────────────────────────────────────────────
  "gpt-4o": {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    apiModel: "gpt-4o",
    contextWindow: 128_000,
    defaultMaxTokens: 16_384,
    pricing: {
      inputPerM: 2.5,
      outputPerM: 10.0,
      cacheReadPerM: 1.25,
    },
    capabilities: ["vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    isDefault: false,
  },
  "gpt-4o-mini": {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "openai",
    apiModel: "gpt-4o-mini",
    contextWindow: 128_000,
    defaultMaxTokens: 16_384,
    pricing: {
      inputPerM: 0.15,
      outputPerM: 0.6,
      cacheReadPerM: 0.075,
    },
    capabilities: ["vision", "tool_calling", "prompt_caching", "streaming", "json_output"],
    isDefault: false,
  },
};
