import type { ModelId, ModelInfo } from "../types.js";

export const xaiModels: Record<ModelId, ModelInfo> = {
  "grok-4.3": {
    id: "grok-4.3",
    name: "Grok 4.3",
    provider: "xai",
    apiModel: "grok-4.3",
    contextWindow: 1_000_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 1.25,
      outputPerM: 2.5,
      cacheReadPerM: 0.2,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "low" },
    isDefault: true,
  },
  "grok-4.20-reasoning": {
    id: "grok-4.20-reasoning",
    name: "Grok 4.20 Reasoning",
    provider: "xai",
    apiModel: "grok-4.20-0309-reasoning",
    contextWindow: 1_000_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 1.25,
      outputPerM: 2.5,
      cacheReadPerM: 0.2,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "streaming", "json_output"],
    reasoningConfig: { defaultEffort: "high" },
    isDefault: false,
  },
  "grok-4.20-non-reasoning": {
    id: "grok-4.20-non-reasoning",
    name: "Grok 4.20 Non-Reasoning",
    provider: "xai",
    apiModel: "grok-4.20-0309-non-reasoning",
    contextWindow: 1_000_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 1.25,
      outputPerM: 2.5,
      cacheReadPerM: 0.2,
    },
    capabilities: ["vision", "tool_calling", "streaming", "json_output"],
    isDefault: false,
  },
  "grok-build-0.1": {
    id: "grok-build-0.1",
    name: "Grok Build 0.1",
    provider: "xai",
    apiModel: "grok-build-0.1",
    contextWindow: 256_000,
    defaultMaxTokens: 128_000,
    pricing: {
      inputPerM: 1.0,
      outputPerM: 2.0,
      cacheReadPerM: 0.2,
    },
    capabilities: ["reasoning", "vision", "tool_calling", "streaming", "json_output"],
    isDefault: false,
  },
};
