/**
 * Compaction summary markers and detectors (shared; no cut-point imports).
 */

import { extractTextFromContent } from "./message-utils.js";

import type { ModelMessage, UIMessage } from "@tanstack/ai";

export const CONVERSATION_SUMMARY_START = "[CONVERSATION SUMMARY]";
export const CONVERSATION_SUMMARY_END = "[END SUMMARY]";

export function isCompactionSummaryText(text: string | undefined | null): boolean {
  if (!text) return false;
  return text.trimStart().startsWith(CONVERSATION_SUMMARY_START);
}

export function isCompactionSummaryModelMessage(message: ModelMessage): boolean {
  if (message.role !== "user") return false;
  return isCompactionSummaryText(extractTextFromContent(message.content));
}

export function isCompactionSummaryUIMessage(message: UIMessage): boolean {
  if (message.role !== "user") return false;
  const textPart = message.parts.find((part) => part.type === "text");
  if (!textPart || textPart.type !== "text") return false;
  return isCompactionSummaryText(textPart.content);
}

/**
 * Find the outer closing marker: the **last** `[END SUMMARY]` that appears solo on its
 * own line (the real wrapper generated by {@link formatCompactionSummaryContent}).
 *
 * Bodies may quote the markers verbatim (e.g. a summary describing the compaction
 * format itself) — those inline occurrences are line-embedded and never treated as
 * the closing marker, so the body is not truncated at a nested `[END SUMMARY]`.
 * This also fixes streaming: nested markers that arrive before the real outer END
 * do not freeze the extracted body at a premature cut.
 *
 * @returns index of the outer closing marker (start of `[END SUMMARY]`), or -1 if none found
 */
function findOuterEndIndex(trimmed: string): number {
  let lastSoloEnd = -1;
  let searchFrom = 0;
  for (;;) {
    const idx = trimmed.indexOf(CONVERSATION_SUMMARY_END, searchFrom);
    if (idx === -1) break;
    const lineStart = trimmed.lastIndexOf("\n", idx - 1) + 1;
    let lineEnd = trimmed.indexOf("\n", idx);
    if (lineEnd === -1) lineEnd = trimmed.length;
    const line = trimmed.slice(lineStart, lineEnd);
    if (line.trim() === CONVERSATION_SUMMARY_END) {
      lastSoloEnd = idx;
    }
    searchFrom = idx + CONVERSATION_SUMMARY_END.length;
  }
  return lastSoloEnd;
}

/** Whether the text contains a solo-line outer closing marker. */
export function hasOuterEndMarker(text: string | undefined | null): boolean {
  if (!text) return false;
  return findOuterEndIndex(text.trimStart()) !== -1;
}

/**
 * Extract the summary body between markers.
 * - Wrapped text → body between {@link CONVERSATION_SUMMARY_START} and the outer
 *   closing marker (last solo-line `[END SUMMARY]`).
 * - Streaming (no solo closing marker yet) → text after start marker to end of string
 * - Unwrapped plain text → trimmed passthrough (e.g. reactive before re-wrap)
 */
export function extractCompactionSummaryBody(text: string): string | undefined {
  const trimmed = text.trimStart();
  if (!trimmed.startsWith(CONVERSATION_SUMMARY_START)) {
    const plain = text.trim();
    return plain || undefined;
  }

  const endIndex = findOuterEndIndex(trimmed);
  const body =
    endIndex === -1
      ? trimmed.slice(CONVERSATION_SUMMARY_START.length)
      : trimmed.slice(CONVERSATION_SUMMARY_START.length, endIndex);
  const result = body.trim();
  return result || undefined;
}

export function formatCompactionSummaryContent(summary: string): string {
  return `${CONVERSATION_SUMMARY_START}

${summary}

${CONVERSATION_SUMMARY_END}

Continue if you have next steps, or stop and ask for clarification if you are unsure how to proceed.`;
}
