import { calculateCost, promptTokensOf, totalTokensOf, type TokenUsage } from "../../runtime-types/token-usage.js";

import type { AgentEventBus } from "../../agent/agent-event-bus";
import type { ModelCapability, ModelPricing } from "../../models/types.js";
import type { UsageChangeSnapshot } from "../../runtime-types/session-payloads.js";

export { extractTanStackProvider, extractTanStackUsage } from "../../runtime-types/token-usage.js";
export { promptTokensOf } from "../../runtime-types/token-usage.js";

// ============================================================================
// UsageTracker
// ============================================================================

const emptyUsage = (): TokenUsage => ({
  inputTokens: 0,
  outputTokens: 0,
  totalTokens: 0,
  cacheReadTokens: 0,
  cacheWriteTokens: 0,
  reasoningTokens: 0,
});

/**
 * Billed prompt of one usage reading — the number the cache counters are a share of.
 *
 * The rule itself lives in `runtime-types/token-usage.js` (beside `calculateCost`), so the
 * tracker and the usage store read the same one rather than each restating it. Re-exported
 * here because this module has been its public home.
 */
export interface UsageSnapshot {
  usage: TokenUsage;
  costUsd?: number;
}

export type { UsageChangeSnapshot } from "../../runtime-types/session-payloads.js";

/**
 * Tracks per-step context window fill and lifetime token usage for a managed agent.
 */
export class UsageTracker {
  /** Current context window fill (input replaced each step; output accumulated per turn). */
  private window: TokenUsage = emptyUsage();

  /** Lifetime totals across compaction cycles. */
  private total: TokenUsage = emptyUsage();

  private totalCostUsd = 0;
  private pricing: ModelPricing | null = null;
  /**
   * Declared capabilities, or `null` when **unknown**.
   *
   * `null` and `[]` are different on purpose: `null` means nothing was declared, so
   * {@link hasCapability} is permissive; `[]` means capabilities were resolved and none apply,
   * so it is strict. Collapsing the two is what previously required a permanently-true
   * capability (`streaming`) to keep the list non-empty.
   */
  private capabilities: ModelCapability[] | null = null;
  private tokenLimit = 0;

  /** Cumulative wall-clock time of measured main-loop LLM calls (ms). */
  private totalLlmMs = 0;

  /**
   * Lifetime billed prompt, accumulated per sample with {@link promptTokensOf}.
   *
   * Kept alongside {@link total} rather than derived from it: `total.inputTokens` is a
   * cache-miss sum under an exclusive upstream, so the prompt cannot be recovered from the
   * aggregate. Accumulating per sample keeps the same rule as the window fill and stays exact
   * under both conventions.
   */
  private billedInputTotal = 0;
  /** Output tokens generated by the measured main-loop LLM calls. */
  private totalLlmOutputTokens = 0;
  /** Cost of the most recent accumulation (main step or side query), for per-call logging. */
  private lastCallCostUsd = 0;
  /** Reasoning tokens of the most recent main step, for per-call logging. */
  private lastCallReasoningTokens = 0;

  /** Unified event bus for the owning agent (session `usage` projection). */
  private eventBus?: AgentEventBus;

  /** @internal Attach the agent's scoped unified event bus. */
  setEventBus(bus: AgentEventBus): void {
    this.eventBus = bus;
    bus.retain("session:usage", () => this.getChangeSnapshot());
  }

  /** Update window usage from a main run step and accumulate into lifetime totals. */
  updateWindowUsage(usage: TokenUsage, pricing?: ModelPricing | null): void {
    const prev = this.window;
    const resolvedPricing = pricing ?? this.pricing;

    this.window = {
      inputTokens: usage.inputTokens,
      outputTokens: prev.outputTokens + usage.outputTokens,
      totalTokens: 0,
      cacheReadTokens: usage.cacheReadTokens ?? 0,
      cacheWriteTokens: usage.cacheWriteTokens ?? 0,
      reasoningTokens: (prev.reasoningTokens ?? 0) + (usage.reasoningTokens ?? 0),
    };
    this.window.totalTokens = this.getContextFillTokens() + this.window.outputTokens;
    this.lastCallReasoningTokens = usage.reasoningTokens ?? 0;

    this.lastCallCostUsd = this.accumulateTotal(usage, resolvedPricing);
    this.emitChange();
  }

  /**
   * Set the window (context fill) without touching lifetime totals.
   *
   * Used when *restoring* window usage from a persisted session: the restored
   * context fill is already included in the restored lifetime totals, so
   * {@link updateWindowUsage} (which accumulates) would count it a second time.
   */
  setWindowUsage(usage: TokenUsage): void {
    this.window = {
      inputTokens: usage.inputTokens,
      outputTokens: usage.outputTokens,
      totalTokens: 0,
      cacheReadTokens: usage.cacheReadTokens ?? 0,
      cacheWriteTokens: usage.cacheWriteTokens ?? 0,
      reasoningTokens: usage.reasoningTokens ?? 0,
    };
    // Same context-fill reading as `updateWindowUsage`: a restored session carries the
    // cache breakdown too, so the fill must not depend on which writer populated it.
    this.window.totalTokens = this.getContextFillTokens() + this.window.outputTokens;
    this.emitChange();
  }

  /** Add usage to lifetime totals only (side queries, title generation, etc.). */
  addTotal(usage: TokenUsage, pricing?: ModelPricing | null): void {
    this.lastCallCostUsd = this.accumulateTotal(usage, pricing ?? this.pricing);
    this.emitChange();
  }

  /**
   * Add usage plus a precomputed cost to lifetime totals without re-pricing.
   * Used when aggregating a subagent's totals into its parent: the subagent
   * already computed each call's cost with its own model's pricing, so the
   * parent must carry the cost over instead of re-computing it at the parent's
   * (possibly different) rate.
   */
  addTotalWithCost(usage: TokenUsage, costUsd: number): void {
    this.accumulateTotal(usage, null);
    this.totalCostUsd += Number.isFinite(costUsd) && costUsd > 0 ? costUsd : 0;
    this.lastCallCostUsd = 0;
    this.emitChange();
  }

  /**
   * Record one measured main-loop LLM call: its wall-clock duration and generated output tokens.
   *
   * Together these yield a generation-rate basis (tok/s) that only counts calls whose
   * duration is actually known — unmeasured aggregation (e.g. subagent totals added via
   * {@link addTotal}) and side-query calls (titles, summaries, memory selection) are
   * excluded, keeping the rate a faithful measure of the agent's own generation speed.
   */
  addLlmCall(durationMs: number, outputTokens: number): void {
    if (!Number.isFinite(durationMs) || durationMs <= 0) return;
    this.totalLlmMs += durationMs;
    this.totalLlmOutputTokens += Number.isFinite(outputTokens) && outputTokens > 0 ? outputTokens : 0;
    this.emitChange();
  }

  getLlmDurationMs(): number {
    return this.totalLlmMs;
  }

  getLlmOutputTokens(): number {
    return this.totalLlmOutputTokens;
  }

  private accumulateTotal(usage: TokenUsage, pricing: ModelPricing | null | undefined): number {
    this.billedInputTotal += promptTokensOf(usage);
    this.total = {
      inputTokens: this.total.inputTokens + usage.inputTokens,
      outputTokens: this.total.outputTokens + usage.outputTokens,
      totalTokens: 0,
      cacheReadTokens: (this.total.cacheReadTokens ?? 0) + (usage.cacheReadTokens ?? 0),
      cacheWriteTokens: (this.total.cacheWriteTokens ?? 0) + (usage.cacheWriteTokens ?? 0),
      reasoningTokens: (this.total.reasoningTokens ?? 0) + (usage.reasoningTokens ?? 0),
    };
    this.total.totalTokens = totalTokensOf(this.total);

    if (!pricing) return 0;
    const callCost = calculateCost(usage, pricing);
    this.totalCostUsd += callCost;
    return callCost;
  }

  getWindowUsage(): Readonly<TokenUsage> {
    return this.window;
  }

  /**
   * True context-window fill in tokens — the number the model actually had in front of it.
   *
   * `window.inputTokens` alone is not it: under an exclusive upstream that field holds only
   * the cache-miss part, so a fully-cached prompt renders as ~0% of a 400k window. Delegates
   * to {@link promptTokensOf}, the one convention-aware reading.
   */
  getContextFillTokens(): number {
    return promptTokensOf(this.window);
  }

  getTotal(): Readonly<TokenUsage> {
    return this.total;
  }

  /**
   * Billed prompt tokens across the session lifetime — what a cache read is a share of.
   *
   * Accumulated **per sample** with the same convention-aware rule as the window fill, so an
   * exclusive session sums `input + cache` rather than collapsing to the larger reading. Not
   * `total.inputTokens`, which under an exclusive upstream is only the cache-miss part: the
   * old ratio divided by it and printed `Cache hit: 428.5%` on a real session.
   */
  getBilledInputTokens(): number {
    return this.billedInputTotal;
  }

  /**
   * Share of the billed prompt served from cache, 0-1.
   *
   * A **ratio of totals**, not a per-call average, so it is the one reading of this data that
   * is valid under both upstream conventions (see {@link promptTokensOf}). Mixing conventions
   * mid-session weakens it, but it stays inside (0,1] either way — which is the property the
   * previous formula lacked.
   */
  getCacheHitRatio(): number {
    const prompt = this.billedInputTotal;
    if (prompt <= 0) return 0;
    return (this.total.cacheReadTokens ?? 0) / prompt;
  }

  getTotalCostUsd(): number {
    return this.totalCostUsd;
  }

  /** Cost of the most recent accumulation (0 when no pricing was configured). */
  getLastCallCostUsd(): number {
    return this.lastCallCostUsd;
  }

  /** Reasoning tokens of the most recent main step. */
  getLastCallReasoningTokens(): number {
    return this.lastCallReasoningTokens;
  }

  setTotalCostUsd(cost: number): void {
    this.totalCostUsd = cost;
    this.emitChange();
  }

  setPricing(pricing: ModelPricing): void {
    this.pricing = pricing;
  }

  getPricing(): ModelPricing | null {
    return this.pricing;
  }

  setCapabilities(caps: ModelCapability[] | undefined): void {
    // `undefined` (no metadata resolved) must stay distinguishable from `[]` (resolved, none
    // apply) all the way to the probe — see the field doc.
    this.capabilities = caps === undefined ? null : [...caps];
  }

  /**
   * Capabilities as reported for the current model, or `null` when unknown.
   *
   * **`null` means unknown**, not "no capabilities" — {@link hasCapability} is permissive for
   * that reason. Use this when you must tell "declared nothing" from "declared none of them".
   */
  getCapabilities(): ReadonlySet<ModelCapability> | null {
    return this.capabilities === null ? null : new Set(this.capabilities);
  }

  hasCapability(cap: ModelCapability): boolean {
    if (this.capabilities === null) return true;
    return this.capabilities.includes(cap);
  }

  setTokenLimit(limit: number): void {
    this.tokenLimit = limit;
  }

  getTokenLimit(): number {
    return this.tokenLimit;
  }

  getTokenLimitPercent(): number {
    if (this.tokenLimit <= 0) return 0;
    return Math.min(100, (this.getContextFillTokens() / this.tokenLimit) * 100);
  }

  resetWindow(): void {
    this.window = emptyUsage();
    this.emitChange();
  }

  reset(): void {
    this.window = emptyUsage();
    this.total = emptyUsage();
    this.billedInputTotal = 0;
    this.totalCostUsd = 0;
    this.totalLlmMs = 0;
    this.totalLlmOutputTokens = 0;
    this.emitChange();
  }

  snapshot(pricing?: ModelPricing | null): UsageSnapshot {
    const resolved = pricing ?? this.pricing;
    return {
      usage: { ...this.total },
      ...(resolved ? { costUsd: this.totalCostUsd || calculateCost(this.total, resolved) } : {}),
    };
  }

  /** Full UI-oriented usage snapshot (totals + window fill). */
  getChangeSnapshot(): UsageChangeSnapshot {
    return {
      total: { ...this.total },
      window: { ...this.window },
      percent: this.getTokenLimitPercent(),
      contextFillTokens: this.getContextFillTokens(),
      billedInputTokens: this.getBilledInputTokens(),
      tokenLimit: this.tokenLimit,
      cost: this.totalCostUsd,
      llmDurationMs: this.totalLlmMs,
      llmOutputTokens: this.totalLlmOutputTokens,
    };
  }

  private emitChange(): void {
    // Session `usage` projection — the bus is the single change mechanism.
    this.eventBus?.emit("session:usage", this.getChangeSnapshot());
  }
}
